name: GitHub 3D Contributions

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contributions

    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D Contribution Stats
        uses: cicirello/generate-3d-contribution-stats@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          background-color: "#0d1117"
          foreground-color: "#00979D"

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update 3d contribution graph"
          add: "*.svg"